version: '3'
services:
  backend:
    build:
      context: app
      dockerfile: backend.dockerfile
    container_name: backend
    env_file: app/backend/.env.dev
    ports:
      - '8080:8080'
    restart: always
  frontend:
    build:
      context: .
      dockerfile: app/frontend.dockerfile
    container_name: frontend
    ports:
      - '80:8080'
    restart: always